http:
  connectTimeoutInMillis: 10000
  keepAliveDurationInMillis: 30000
  maxIdleConnections: 100
  idleConnectionTimeoutInMillis: 90000
  tlsHandshakeTimeoutInMillis: 10000
  expectContinueTimeoutInMillis: 1000
  timeoutInMillis: 15000
counter:
  queryTimeoutInMillis: 5000