basePath: /
info:
  contact:
    email: AmxTechTeamInternal@angelbroking.com
    name: Team AMX
  description: AMX Report - Position Report, Trade Report, Order Report
  termsOfService: https://swagger.io/terms/
  title: AMX Reports
  version: "1.0"
paths:
  /CGI/PositionReport:
    post:
      description: Provides position, trade, order and other reports
      parameters:
      - description: 201|A599059|A599059|26F638C8EADE24F38A6480D7EB53DA||||
        in: body
        name: request
        schema:
          type: string
      responses:
        "200":
          description: 251|0|0000306|nse_cm|1594|A599059|CNC|INFY-EQ|INFY||EQ||-1||1|2|-1|INFOSYS
            LIMITED|1|5|1|1|1|1|1|0|171555|0|0|0|0|0|171555|0|171555|-171555|1|171555|0|0|0|171555|0|171555^nse_cm|22|A599059|CNC|ACC-EQ|ACC||EQ||-1||1|2|-1|ACC
            LIMITED|1|5|1|1|1|1|2|0|451510|0|0|0|0|0|225755|0|225755|-451510|2|451510|0|0|0|225755|0|225755^
          schema:
            type: string
        "400":
          description: 250|2|0018|Error
          schema:
            type: string
      summary: Position Report
      tags:
      - Position Report API V1
securityDefinitions:
  AuthorizationBearerToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
