basePath: /
info:
  contact:
    email: AmxTechTeamInternal@angelbroking.com
    name: Team AMX
  description: Load test of websockets
  termsOfService: https://swagger.io/terms/
  title: WS Load Test
  version: "1.0"
paths:
  /latency:
    get:
      description: latency
      summary: Latency
      tags:
      - Latency API V1
  /welcome:
    get:
      description: welcome
      summary: Welcome
      tags:
      - Welcome API V1
swagger: "2.0"
